// AUTO-GENERATED by scripts/gen-message-index.mjs
import ns_ai from "./ai.json";
import ns_calendar from "./calendar.json";
import ns_cat from "./cat.json";
import ns_coach from "./coach.json";
import ns_common from "./common.json";
import ns_family from "./family.json";
import ns_find from "./find.json";
import ns_help from "./help.json";
import ns_interests from "./interests.json";
import ns_me from "./me.json";
import ns_nav from "./nav.json";
import ns_offline from "./offline.json";
import ns_opp from "./opp.json";
import ns_plan from "./plan.json";
import ns_privacy from "./privacy.json";
import ns_progress from "./progress.json";
import ns_resume from "./resume.json";
import ns_school from "./school.json";
import ns_settings from "./settings.json";
import ns_staff from "./staff.json";
import ns_tracker from "./tracker.json";
import ns_welcome from "./welcome.json";
import ns_wellbeing from "./wellbeing.json";

const messages = {
  "ai": ns_ai,
  "calendar": ns_calendar,
  "cat": ns_cat,
  "coach": ns_coach,
  "common": ns_common,
  "family": ns_family,
  "find": ns_find,
  "help": ns_help,
  "interests": ns_interests,
  "me": ns_me,
  "nav": ns_nav,
  "offline": ns_offline,
  "opp": ns_opp,
  "plan": ns_plan,
  "privacy": ns_privacy,
  "progress": ns_progress,
  "resume": ns_resume,
  "school": ns_school,
  "settings": ns_settings,
  "staff": ns_staff,
  "tracker": ns_tracker,
  "welcome": ns_welcome,
  "wellbeing": ns_wellbeing,
};
export default messages;
