// AUTO-GENERATED by scripts/gen-message-index.mjs
import ns_common from "./common.json";
import ns_nav from "./nav.json";
import ns_settings from "./settings.json";

const messages = {
  "common": ns_common,
  "nav": ns_nav,
  "settings": ns_settings,
};
export default messages;
