// AUTO-GENERATED by scripts/gen-message-index.mjs
import ns_common from "./common.json";
import ns_find from "./find.json";
import ns_nav from "./nav.json";
import ns_opp from "./opp.json";
import ns_settings from "./settings.json";
import ns_welcome from "./welcome.json";

const messages = {
  "common": ns_common,
  "find": ns_find,
  "nav": ns_nav,
  "opp": ns_opp,
  "settings": ns_settings,
  "welcome": ns_welcome,
};
export default messages;
