// AUTO-GENERATED by scripts/gen-message-index.mjs
import ns_ai from "./ai.json";
import ns_cat from "./cat.json";
import ns_coach from "./coach.json";
import ns_common from "./common.json";
import ns_find from "./find.json";
import ns_help from "./help.json";
import ns_interests from "./interests.json";
import ns_me from "./me.json";
import ns_nav from "./nav.json";
import ns_offline from "./offline.json";
import ns_opp from "./opp.json";
import ns_plan from "./plan.json";
import ns_privacy from "./privacy.json";
import ns_settings from "./settings.json";
import ns_welcome from "./welcome.json";

const messages = {
  "ai": ns_ai,
  "cat": ns_cat,
  "coach": ns_coach,
  "common": ns_common,
  "find": ns_find,
  "help": ns_help,
  "interests": ns_interests,
  "me": ns_me,
  "nav": ns_nav,
  "offline": ns_offline,
  "opp": ns_opp,
  "plan": ns_plan,
  "privacy": ns_privacy,
  "settings": ns_settings,
  "welcome": ns_welcome,
};
export default messages;
